### ISSUE TITLE
Issue w/ auto deploy in Rancher (may exist with docker-compose as well)

### ISSUE THREAD

**Issue by DACRepair** [zammad/zammad-docker-compose#38]
### Infos:

* Docker version:17.03.1-ce
* Docker-compose version: Rancher 1.5.5 (builtin composer?)
* Operating system (Docker host): Debian 8

### Expected behavior:

* Zammad installed from the catalogs should start

### Actual behavior:

* Install shows all services green, however the railsserver is stalled "Waiting for postgresql server"

### Steps to reproduce the behavior:

* Install from the catalogue

I have installed Zammad 1.2 from the Rancher catalogues, and it hangs after install. All containers show green, however it always has a 502 gateway failure. After some investigation i found the railsserver container was sitting at waiting for postgresql. upon looking at the Dockerfile, I noticed it waits for a server at service link "zammad-postgresql" when the actual link name is "postgresql". I tried doing a service upgrade and renamed the link to "zammad-postgresql", and it fired right up.

**Comment by monotek** [comment]
Hope its fixed with updated rancher file: https://github.com/rancher/community-catalog/pull/617

**Comment by DACRepair** [comment]
This didn't fix it, however I was able to clear up the issue with the addition of a service link (when using rancher to execute the compose file from the catalogue, the postgres server gets named "postgresql", and the railsserver entrypoint script is expecting "zammad-postgresql". I added another postgres service link with that name and it fired right up.

**Comment by monotek** [comment]
The catalogue is deprecated. Please use the yml file from our repo.
Tried it today without problems. Closing.
